swagger: '2.0'
info:
  title: OndeParar
  description: API para indicar vagas para estacionar na rua, desenvolvida pelo grupo 09.
  version: "1.0.0"
host: grupo09.ondeparar.com
schemes:
  - https
basePath: /v1
produces:
  - application/json
paths:
  /Enderecos:
    get:
      summary: Endereços das Vagas.
      description: |
        O endpoint de enderecos retorna os enderecos de todas as vagas previamente cadastradas. Esse retorno contém a localização e as características do endereço.
      tags:
        - Enderecos
      responses:
        200:
          description: Local e características do endereco.
          schema:
            type: array
            items:
              $ref: '#/definitions/Endereco'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: Não é possível postar para esse endpoint.
      tags:
        - Enderecos
      responses:
        405:
          description: Method not allowed
  /Endereco/{id}:
    get:
      summary: Descrição de um Endereço.
      description: |
        Esse endpoint retorna os dados do Endereco passado no parâmetro {id}.
      tags:
        - Enderecos
      parameters:
          - name: id
            in: path
            required: true
            type: number
            format: double
      responses:
        200:
          description: Descrição do Endereco.
          schema:
            type: object
            items:
              $ref: '#/definitions/Endereco'
        401:
          description: Retorna erro quando se tenta acessar o recurso sem autenticação.
          schema:
            type: object
            items:
              $ref: '#/definitions/Endereco'
        403:
          description: Retorna erro quando se tenta acessar o recurso sem autorização.
          schema:
            type: object
            items:
              $ref: '#/definitions/Endereco'
        404:
          description: Nenhum endereco encontrado para o id fornecido.
          schema:
            type: object
            items:
              $ref: '#/definitions/Endereco'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /Endereco/{id}/Vagas:
    get:
      summary: Vagas em um determinado Endereco (rua, avenidad etc.).
      description: |
        Esse endpoint retorna as Vagas constantes no Endereco.
      tags:
        - Enderecos
      parameters:
          - name: id
            in: path
            required: true
            type: string
      responses:
        200:
          description: Quantidade de Vagas e se há Vaga livre.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        401:
          description: Retorna erro quando se tenta acessar o recurso sem autenticação.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        403:
          description: Retorna erro quando se tenta acessar o recurso sem autorização.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        404:
          description: Nenhuma Vaga encontrado para o Endereco fornecido.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error' 
  /Endereco/{lat},{long}/Vagas:
    get:
      summary: Vagas em uma dada coordenada.
      description: |
        Esse endpoint retorna as Vagas constantes na coordenada.
      tags:
        - Enderecos
      parameters:
          - name: lat
            in: path
            required: true
            type: number
            format: double
          - name: long
            in: path
            required: true
            type: number
            format: double
      responses:
        200:
          description: Quantidade de Vagas e se há Vaga livre.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        401:
          description: Retorna erro quando se tenta acessar o recurso sem autenticação.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        403:
          description: Retorna erro quando se tenta acessar o recurso sem autorização.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        404:
          description: Nenhuma Vaga encontrado para as coordenadas fornecidas.
          schema:
            type: object
            items:
              $ref: '#/definitions/EnderecoVaga'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'  
    
definitions:
  Endereco:
    type: object
    properties:  
      id:
       type: string 
       description: Chave primária que diferencia um Endereco.
      logradouro:
       type: string
       description: Nome da rua, avenida etc.
      cep:
        type: string
        description: CEP do Endereco.
      bairro:
        type: string 
        description: Bairro do Endereco.
      cidade:
        type: string
        description: Cidade do Endereco.
      estado:
        type: string
        description: Estado do Endereco.
      pais:
        type: string
        description: País do Endereco.
      zonaAzul:
        type: boolean
        description: Se o Endereco possui Zona Azul.
      localidadePerigosa: 
        type: boolean
        description: Se o Endereco é considerado perigoso.
      incidenciaFlanelinha:
        type: string
        description: Assiduidade de Flanelinhas no Endereco.
      latitude: 
        type: number
        description: Coordenada Latitude do Endereco.
        format: double
      longitude:
        type: number
        description: Coordenada Longitude do Endereco.
        format: double
  EnderecoVaga:
    type: object
    properties: 
      id: 
        description: Chave primária que diferencia cada endereco ou coordenada de vagas.
        type: string
      quantidade: 
        description: Quantidade total de vagas cadastradas para o(s) parametro(s) fornecido(s).
        type: integer
      estado:
        description: Se há ao menos uma vaga livre, ou se todas estão ocupadas.
        type: string
  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
      fields:
        type: string
